title: "Alyssia Art"
description: "A new art project by Alyssia"
author: "Alyssia"
plugins:
  - jekyll-include-cache
remote_theme: mmistakes/minimal-mistakes
defaults:
  - scope:
      path: "_posts"
      type: posts
  
